variable "aws_region" {}
variable "VPC_cidr_block" {}
variable "VPC_Name" {}
variable "ASG_VPC_Public_Subnet" {}
variable "azs" {}
variable "ASG_VPC_Private_Subnet" {}
variable "ASG_VPC_SG" {}
variable "key_name" {}
variable "EC2-Name" {}